=== BuddhistDigitalResourceCenter/xmltoldmigration/src/main/resources/xsd/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c="http://www.tbrc.org/models/common#"
    targetNamespace="http://www.tbrc.org/models/person#" xmlns:per="http://www.tbrc.org/models/person#"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xsd:import namespace="http://www.tbrc.org/models/common#" schemaLocation="common.xsd"/>
    <!-- root elements for TBRC: person -->
    <xsd:element name="person" type="per:Person"/>
    <xsd:complexType name="Person">
        <xsd:annotation>
            <xsd:documentation>The Person object tracks biographical
                data such as kinship relations, birth and death dates, administrative offices 
                and seats held, important events and known name variants.  Instances of Person objects
                are created for historical and quasi-historical personages, including legendary and mythical
                figures. Deities are defined as Topics. </xsd:documentation>
        </xsd:annotation>
        <xsd:group ref="per:PersonElems"/>
        <xsd:attribute name="RID" type="c:personRID" use="required"/>
        <xsd:attribute name="status" type="c:statusTypeAttr" default="editing"/>
    </xsd:complexType>
    <xsd:group name="PersonElems">
        <xsd:annotation>
            <xsd:documentation>The Person object tracks biographical
                data such as kinship relations, birth and death dates, administrative offices 
                and seats held, important events and known name variants.  Instances of Person objects
                are created for historical and quasi-historical personages, including legendary and mythical
                figures. Deities are defined as Topics. </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="name" type="per:Name" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:group ref="per:OtherPersonElems" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="log" type="c:AuditLog" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:group>
    <xsd:group name="OtherPersonElems">
        <xsd:annotation>
            <xsd:documentation>The Person object tracks biographical
                data such as kinship relations, birth and death dates, administrative offices 
                and seats held, important events and known name variants.  Instances of Person objects
                are created for historical and quasi-historical personages, including legendary and mythical
                figures. Deities are defined as Topics. </xsd:documentation>
        </xsd:annotation>
        <xsd:choice>
            <xsd:element name="info" type="per:Info" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="event" type="per:Event" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="seat" type="per:Seat" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="studentOf" type="per:StudentOf" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="teacherOf" type="per:TeacherOf" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="kinship" type="per:KinshipRelation" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="incarnationOf" type="per:IncarnationRelation" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ofSect" type="per:SectRelation" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="classification" type="c:Classification" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="external" type="c:ExternalEntry" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="note" type="c:Note" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
    </xsd:group>
    <xsd:complexType name="Name">
        <xsd:annotation>
            <xsd:documentation>In Tibetan culture, a person often has many different names depending on
                religious, political, clan or social affiations.  Cataloging name variants allows
                TBRC to properly define biographical entries according to Tibetan customs.</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="c:langTypeAttr" default="tibetan"/>
                <xsd:attribute name="encoding" type="c:langEncTypeAttr" default="extendedWylie"/>
                <xsd:attribute name="type" type="per:nameTypeAttr" default="primaryName"/>
                <xsd:attribute name="type-tib" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="Info">
        <xsd:annotation><xsd:documentation>Person Info is currently limited to gender but could be expanded to include other
            kinds of information.</xsd:documentation></xsd:annotation>
        <xsd:attribute name="gender" type="per:genderTypeAttr" default="male"/>
        <xsd:attribute name="type" type="per:personTypeAttr" default="actor"/>
    </xsd:complexType>
    <xsd:complexType name="Event">
        <xsd:annotation>
            <xsd:documentation>Person Events are usually historical events of interest that 
                involve an Office and Place and an optional year.</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="office" type="per:Office" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="place" type="per:Place" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="corp" type="per:Corporation" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="pid" type="c:anyRID"/>
        <xsd:attribute name="type" type="c:eventTypeAttr"/>
        <xsd:attribute name="circa" type="xsd:string" use="optional"/>
    </xsd:complexType>
    <xsd:complexType name="Seat">
        <xsd:sequence>
            <xsd:element name="place" type="per:Place"/>
        </xsd:sequence>
        <xsd:attribute name="circa" type="xsd:string" use="optional"/>
    </xsd:complexType>
    <xsd:complexType name="Office">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="pid" type="c:officeRID"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="Corporation">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="pid" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="SectRelation">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="sect" type="c:topicRID"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="Place">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="pid" type="c:placeRID"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="RelatedPerson">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="pid" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="StudentOf">
        <xsd:simpleContent>
            <xsd:extension base="per:RelatedPerson"/>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="TeacherOf">
        <xsd:simpleContent>
            <xsd:extension base="per:RelatedPerson"/>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="KinshipRelation">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="relation" type="per:kinshipRelationType"/>
                <xsd:attribute name="person" type="c:personRID"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="IncarnationRelation">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="relation" type="per:incarnationRelationType" use="optional"/>
                <xsd:attribute name="secondary" type="per:incarnationRelationType" use="optional"/>
<!-- not possible is XSD 1.0               <xsd:assert test="(@relation and not(@secondary)) or (not(@relation) and @secondary)"/>-->
                <xsd:attribute name="being" type="per:beingRID" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:simpleType name="beingRID">
        <xsd:union memberTypes="c:personRID c:topicRID"/>
    </xsd:simpleType>    
    <xsd:simpleType name="nameTypeAttr">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="commonName"/>
            <xsd:enumeration value="primaryName"/>
            <xsd:enumeration value="primaryTitle"/>
            <xsd:enumeration value="personalName"/>
            <xsd:enumeration value="tulkuTitle"/>
            <xsd:enumeration value="officeTitle"/>
            <xsd:enumeration value="gterStonTitle"/>
            <xsd:enumeration value="title"/>
            <xsd:enumeration value="familyName"/>
            <xsd:enumeration value="firstOrdinationName"/>
            <xsd:enumeration value="finalOrdinationName"/>
            <xsd:enumeration value="bodhisattvaVowName"/>
            <xsd:enumeration value="secretInitiatoryName"/>
            <xsd:enumeration value="chineseName"/>
            <xsd:enumeration value="otherName"/>
            <xsd:enumeration value="reversal"/>
            <xsd:enumeration value="sanskrit"/>
            <xsd:enumeration value="grammatical"/>
            <xsd:enumeration value="variantOrthography"/>
            <xsd:enumeration value="penName"/>
            <xsd:enumeration value="corporateName"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="genderTypeAttr">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="male"/>
            <xsd:enumeration value="female"/>
            <xsd:enumeration value="unknown"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="personTypeAttr">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="nonActor"/>
            <xsd:enumeration value="actor"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="kinshipRelationType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="hasSon"/>
            <xsd:enumeration value="hasFather"/>
            <xsd:enumeration value="hasMother"/>
            <xsd:enumeration value="hasUncle"/>
            <xsd:enumeration value="hasSister"/>
            <xsd:enumeration value="hasBrother"/>
            <xsd:enumeration value="hasAunt"/>
            <xsd:enumeration value="hasDaughter"/>
            <xsd:enumeration value="hasCousin"/>
            <xsd:enumeration value="hasGrandmother"/>
            <xsd:enumeration value="hasGrandfather"/>
            <xsd:enumeration value="hasSisterInLaw"/>
            <xsd:enumeration value="hasBrotherInLaw"/>
            <xsd:enumeration value="hasNephew"/>
            <xsd:enumeration value="hasNiece"/>
            <xsd:enumeration value="hasGranddaughter"/>
            <xsd:enumeration value="hasGrandson"/>
            <xsd:enumeration value="hasWife"/>
            <xsd:enumeration value="hasHusband"/>
            <xsd:enumeration value="hasYoungerBrother"/>
            <xsd:enumeration value="hasOlderBrother"/>
            <xsd:enumeration value="hasYoungerSister"/>
            <xsd:enumeration value="hasOlderSister"/>
            <xsd:enumeration value="hasMaternalUncle"/>
            <xsd:enumeration value="hasPaternalUncle"/>
            <xsd:enumeration value="hasMaternalAunt"/>
            <xsd:enumeration value="hasPaternalAunt"/>
            <xsd:enumeration value="hasConsort"/>
            <xsd:enumeration value="incarnationOf"/>
            <xsd:enumeration value="hasIncarnation"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="incarnationRelationType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="general"/>
            <xsd:enumeration value="yangtse"/>
            <xsd:enumeration value="body"/>
            <xsd:enumeration value="speech"/>
            <xsd:enumeration value="mind"/>
            <xsd:enumeration value="qualities"/>
            <xsd:enumeration value="activities"/>
        </xsd:restriction>
    </xsd:simpleType>    
</xsd:schema>

=== BuddhistDigitalResourceCenter/xmltoldmigration/src/test/xml/P1331.xml
<p:person xmlns:p="http://www.tbrc.org/models/person#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" RID="P1331" status="released" xsi:schemaLocation="http://www.tbrc.org/models/person# person.xsd">
    <p:name lang="tibetan" encoding="extendedWylie" type="primaryName">blo gros rnam dag</p:name>
    <p:name lang="tibetan" encoding="extendedWylie" type="primaryTitle">bya yul blo bzang rnam dag</p:name>
    <p:info gender="male"/>
    <p:event pid="E7285" type="death" circa="1322"/>
    <p:seat>
        <p:place pid="G844">bya yul</p:place>
    </p:seat>
    <p:teacherOf pid="P1323">don grub dpal ba</p:teacherOf>
    <p:note work="W20115" location="p. 359">date of death from this source</p:note>
</p:person>

=== BuddhistDigitalResourceCenter/xmltoldmigration/src/test/xml/P1583.xml
<p:person xmlns:p="http://www.tbrc.org/models/person#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" RID="P1583" status="released" xsi:schemaLocation="http://www.tbrc.org/models/person# http://www.tbrc-dlms.org/tbrc-defs/1/0/person.xsd">
    <p:name encoding="extendedWylie" lang="tibetan" type="primaryName">dri med 'od zer/

</p:name>
    <p:name encoding="extendedWylie" lang="tibetan" type="primaryTitle">klong chen rab 'byams pa dri med 'od zer/



</p:name>
    <p:name encoding="extendedWylie" lang="tibetan" type="title">klong chen rab 'byams/




</p:name>
    <p:name encoding="extendedWylie" lang="tibetan" type="commonName">klong chen pa/

</p:name>
    <p:name encoding="extendedWylie" lang="tibetan" type="personalName">tshul khrims blo gros/





</p:name>
    <p:name encoding="extendedWylie" lang="tibetan" type="title">bsam yas lung mang ba/



</p:name>
    <p:name type="secretInitiatoryName">rgyal sras thugs mchog rtsal/</p:name>
    <p:name encoding="native" lang="chinese" type="primaryName">隆钦热降巴·赤墨俄色</p:name>
    <p:info gender="male"/>
    <p:event circa="1308" pid="E1988" type="birth">
        <p:place pid="G967">g.yo ru stod grong</p:place>
    </p:event>
    <p:event circa="1364" pid="E1989" type="death"/>
    <p:seat>
        <p:place pid="G521">shug gseb dgon (chu shur rdzong)</p:place>
    </p:seat>
    <p:studentOf pid="P1584">bstan pa srung</p:studentOf>
    <p:studentOf pid="P1586">bsam 'grub rin chen</p:studentOf>
    <p:studentOf pid="P1587">kun dga' 'od zer</p:studentOf>
    <p:studentOf pid="P1588">bkra shis rin chen</p:studentOf>
    <p:studentOf pid="P2085">blo gros brtan pa</p:studentOf>
    <p:studentOf pid="P2349">gzhon nu rgyal po</p:studentOf>
    <p:studentOf pid="P4312">g.yag sde paN chen</p:studentOf>
    <p:studentOf pid="P403"> dbang phyug ye shes </p:studentOf>
    <p:studentOf pid="P2JM183">za lung rin po che</p:studentOf>
    <p:studentOf pid="P2JM184">gzhon nu don grub</p:studentOf>
    <p:studentOf pid="P2JM185">gzhon nu rdo rje</p:studentOf>
    <p:studentOf pid="P2JM186">btsan dgon pa </p:studentOf>
    <p:studentOf pid="P2JM187">chos dpal rgyal mtshan</p:studentOf>
    <p:studentOf pid="P4860"> gzhon nu rin chen </p:studentOf>
    <p:studentOf pid="P1226"> bsod nams rgyal mtshan </p:studentOf>
    <p:studentOf pid="P2JM188">khro phu pa</p:studentOf>
    <p:studentOf pid="P2JM189">tshong 'dus pa </p:studentOf>
    <p:studentOf pid="P2JM190">sangs rgyas grags 'od</p:studentOf>
    <p:studentOf pid="P144"> grags pa rgyal mtshan </p:studentOf>
    <p:studentOf pid="P66"> rang byung rdo rje </p:studentOf>
    <p:studentOf pid="P2JM191">dbang ye</p:studentOf>
    <p:teacherOf pid="P6861">chos grags bzang po</p:teacherOf>
    <p:teacherOf pid="P8527">khyab brdal lhun grub</p:teacherOf>
    <p:teacherOf pid="P8528">grags pa 'od zer</p:teacherOf>
    <p:teacherOf pid="P8764">bkra shis 'byung gnas</p:teacherOf>
    <p:teacherOf pid="P8784">ye shes rab 'byams</p:teacherOf>
    <p:teacherOf pid="P2JM192">bde legs rgya mtsho</p:teacherOf>
    <p:teacherOf pid="P5092"> dpal 'byor rgya mtsho </p:teacherOf>
    <p:teacherOf pid="P2JM193">sangs rgyas kun dga' </p:teacherOf>
    <p:teacherOf pid="P5911"> blo gros bzang po </p:teacherOf>
    <p:teacherOf pid="P2JM195">chos kyi grags pa </p:teacherOf>
    <p:teacherOf pid="P2JM196">bzod pa grags pa </p:teacherOf>
    <p:teacherOf pid="P2JM197">dpal mchog</p:teacherOf>
    <p:teacherOf pid="P2JM198">gzhon nu sangs rgyas</p:teacherOf>
    <p:teacherOf pid="P2JM199">pha rgod rtogs ldan rgyal po </p:teacherOf>
    <p:teacherOf pid="P2JM200">'od zer go cha</p:teacherOf>
    <p:teacherOf pid="P2JM201">'od gsal rang grol</p:teacherOf>
    <p:teacherOf pid="P2JM202">bsod nams 'od zer </p:teacherOf>
    <p:teacherOf pid="P2JM203">sangs rgyas dbon po </p:teacherOf>
    <p:teacherOf pid="P2JM204">bsod nams seng+ge</p:teacherOf>
    <p:teacherOf pid="P2JM205">'o rgyan chos rje </p:teacherOf>
    <p:teacherOf pid="P2JM206">grags dpal</p:teacherOf>
    <p:teacherOf pid="P2JM207">sangs rgyas dpal rin </p:teacherOf>
    <p:teacherOf pid="P7091"> bya bral chos rje </p:teacherOf>
    <p:teacherOf pid="P314"> 'jigs med gling pa mkhyen brtse 'od zer </p:teacherOf>
    <p:kinship person="P1584" relation="hasFather">bstan pa srung</p:kinship>
    <p:kinship person="P1585" relation="hasMother">'brom bza' bsod nams rgyan</p:kinship>
    <p:external data="http://example.com">External example</p:external>
    <p:incarnationOf relation="yangtse" being="P561654">ignoring string</p:incarnationOf>
    <p:incarnationOf secondary="mind" being="P561654">ignoring string</p:incarnationOf>
    <p:ofSect sect="T1234">ignoring string</p:ofSect>
    <p:note location="v. 2, pp.104-112" work="W25268">biography
dates: 1308-1363</p:note>
    <p:note>Teachers (not recorded):
Slob-dpon Dbang-ye, Ston-tshul, Khro-phu-ba, Rin-po-che Za-lung-pa (Zhang Tshal-pa'i Gdams ngag and Rgod-tshang-pa's teachings)
1319. Takes rab-byung vows from the abbot of Bsam-yas Bsam-grub-rin-chen.
1326. Enrolls in Gsang-phu Ne'u-thog for formal studies with Mkhan-rabs 15 Slob-dpon Btsan-rgod-pa and Mkhan-rabs 16 Bla-brang Chos-dpal-rgyal-mtshan.
1338. Comes to Snye-phu Shug-gseb and teaches Snying thig.</p:note>
    <p:note location="p. 77" work="W19801"/>
    <p:note location="p. 6" work="W19822"/>
    <p:note>L. v.d. Kuijp has verified that the date of death of the subject was January, 1364. Also the unrecorded teacher Ston tshul may have been Btsun pa Ston tshul, Sa-skya scholar and author of at least two works on Tshad ma.</p:note>
    <p:note location="251" work="W27401">biodata

Subsequent main lineage holders include lha btsun chen po/ gter chen 'gyur med rdo rje/ 'bri gung rin chen phun tshogs/ rig 'dzin 'jigs med gling pa/ mi 'gyur nam mkha'i rdo rje/ 'jam dbyangs mkhyen brtse'i dbang po

Among them, 'jigs med gling pa received the nye brgyud via direct vision of klong chen pa.  'jigs med gling pa passed his lineage to rdo grub phrin las 'od zer, who passed it to mi 'gyur nam mkha' rdo rje, who in turn had a vision of klong chen pa and received the yang tig from him. </p:note>
    <p:log>
        <entry when="2008-06-30T17:01:56.496Z" who="Joe McClellan">added records </entry>
        <entry when="2008-07-02T17:03:41.750Z" who="Joe McClellan">added records</entry>
        <entry when="2009-10-22T18:31:49.120Z" who="Karma Gongde">added name rgyal sras thugs mchog rtsal</entry>
        <entry when="2011-04-27T12:51:43.397Z" who="Paldor">bcos</entry>
        <entry when="2011-07-01T04:41:07.905Z" who="Michael Sheehy">edited names</entry>
        <entry when="2011-08-02T16:53:12.770Z" who="Chungdak Nangpa">added name in chinese</entry>
        <entry when="2012-06-11T09:58:04.367Z" who="Michael R. Sheehy">edited note</entry>
        <entry when="2012-08-23T16:40:14.673Z" who="Jeff Wallman">corrected title and name variant designations</entry>
    </p:log>
</p:person>
